# compose.yaml
name: whatsapp-express-baileys

services:
  app:
    build:
      context: .   # uses your Dockerfile in this folder
    image: whatsapp-express-baileys:latest
    container_name: wa-express-baileys
    restart: unless-stopped
    network_mode: host
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      HOST: 0.0.0.0
      WEBHOOK_URL: "http://localhost:3001/whatsapp" # Now localhost will work since using host network
    volumes:
      - wa-auth:/app/auth   # persist WhatsApp session so you don't re-scan QR
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  wa-auth:
